### ISSUE TITLE
New release support

### ISSUE THREAD

**Issue by fechy** [arturogutierrez/AndEngineSpriterExtension#2]
Hi,

I was wondering if we can work together on having this extension up to date. My java skills are limited, but I have some experience on AndEngine. Although are not suffice to make it all work :(

I hope we can do something. Cheers

**Comment by coccor** [comment]
I think we should direct our attention to Spine. http://www.kickstarter.com/projects/esotericsoftware/spine
Spriter is good, but I think Spine is way better.

**Comment by fechy** [comment]
Yes, I saw it. Is way better and neat. I have being trying to migrate the Libgdx extension with no success yet. Mostly because my knowledge in limited. Check my repos and you'll find a petty implementation with no success on printing the sprites.
I contacted the creators of Spine, and since they are part of the Libgdx team, they wont spend any time on AndEngine :(

**Comment by yhuiyang** [comment]
@fechy, I did minor modification on Arturo's spriter extension. it works on GLES2-AC branch now. Arturo really did a good job, so the modification is really insignificant.

**Comment by arturogutierrez** [comment]
Sorry guys, I've migrated to Cocos2d-x with Spine but it should not be hard to make a port starting from Cocos2d port.

@yhuiyang Thanks, I'm glad this was useful for you :smiley:
